### ISSUE TITLE
Noise estimation

### ISSUE THREAD

**Issue by JohnAshburner** [balbasty/nitorch#58]
Noise estimation with the Rice mixture sometimes uses the variance for the wrong Rice distribution - particularly if image noise is closer to non-central chi.  I'd guess the code uses the one with the smaller mean parameter, but this is sometimes not the background class because a parameter of zero with a large variance might be a better fit to the intensity distribution within the head.  Maybe it would be better to select the one with the smaller expectation:

% https://en.wikipedia.org/wiki/Rice_distribution
t  = -nu.^2./(2*sig2);
% $L_{1/2}(t)$ is computed by:
L  = (1-t).*besseli(0,-t/2,1)...
        -t.*besseli(1,-t/2,1);
% Mean (expectation) of Rice distribution
f  = sqrt(pi*sig2/2)*L

**Comment by JohnAshburner** [comment]
Sorry. Bad use of markdown. This is better...

```
% https://en.wikipedia.org/wiki/Rice_distribution
t  = -nu.^2./(2*sig2);
% $L_{1/2}(t)$ is computed by:
L  = (1-t).*besseli(0,-t/2,1)...
        -t.*besseli(1,-t/2,1);
% Mean (expectation) of Rice distribution
f  = sqrt(pi*sig2/2)*L
```

**Comment by brudfors** [comment]
Hi @JohnAshburner 

That should actually already be the case:

https://github.com/balbasty/nitorch/blob/b8728103cc33285509e6f157f20265f57b38dad4/nitorch/vb/mixtures.py#L481

(I just implemented it the way you are doing it in spm_noise_estimate)

**Comment by balbasty** [comment]
Maybe I am not using your function correctly Mikael. In estimate_noise, it seems to me that if mu_noise is not provided, the class with smallest variance is assumed to be the noise class. What should I provide as "mu_noise"? John suggests to use the class with smallest mean instead of smallest variance.

**Comment by balbasty** [comment]
We currently use the class with smallest sd (I think). Alternatives are: using the class with smallest mean parameter (i.e. the parameter returned by the RMM class), or the class with smallest *expected mean*. John suggests using the latter because when the data is in reality chi distributed instead of rice, the order of the mean parameters can be different from the order of the expected value (?)

**Comment by balbasty** [comment]
Oh I misread you. So currently the RMM class returns the expected value of the distribution, not the mean parameter?

**Comment by brudfors** [comment]
Yes, it should return exactly what JA proposes.

**Comment by balbasty** [comment]
Ok I'll see if the switch works and will maybe rename the output of estimate_noise so it's clearer. Thanks for the help!

**Comment by JohnAshburner** [comment]
I haven't actually checked the code, but for some reason Klara was getting very high noise estimates compared on a dataset compared to what we were getting with a mixture of two chi distributions.  My guess was that it was choosing the Rice distribution with the smaller mean parameter.  It seems there must be another reason for the difference.

**Comment by JohnAshburner** [comment]
Taking the smaller variance should also be fine.  For the `t1w_mfc_3dflash_v1i_R4_0015/anon_s2018-02-28_18-26-190921-00001-00224-1.nii` file from the MPM example dataset, I get a variance estimate of  320.3 using `spm_noise_estimate.m` (Rice mixture) and 539.0 from fitting a mixture of chi distributions.  I'm not sure what nitorch would give.

Klara's nitorch experiments gave variances of 2856.5, 3392.1 and 2847.7 for the three runs, whereas our chi mixture model implementation gave an overall variance estimate of 386.8.  This makes quite a difference to the strength of the denoising.

**Comment by brudfors** [comment]
Where can I find the example dataset? I will try it myself :)

**Comment by JohnAshburner** [comment]
The link from [https://hmri-group.github.io/hMRI-toolbox/](https://hmri-group.github.io/hMRI-toolbox/) takes you to [https://hmri-group.github.io/hMRI-toolbox/](https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ).

**Comment by JohnAshburner** [comment]
Meant to say it takes you to [https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ](https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ).

**Comment by brudfors** [comment]
nitorch's noise estimate gives a variance of 322.9 for `t1w_mfc_3dflash_v1i_R4_0015/anon_s2018-02-28_18-26-190921-00001-00224-1.nii`, so very simillar to SPM I'd say.

**Comment by brudfors** [comment]
Do you know what images Clara used for her experiments?

**Comment by JohnAshburner** [comment]
All very strange. She used the example hMRI dataset.  Perhaps she forked an old version of nitorch, or a bug has since been introduced somewhere.  My own Python skills are not up to the job of tracking down the problem.

I think I'm probably wasting your time, so maybe the issue should be closed.

**Comment by brudfors** [comment]
There might still be a bug, maybe we can add Clara to this discussion, and I could ask her? Do you know if she has a github username?

**Comment by brudfors** [comment]
I will try to compare on the hMRI dataset!

**Comment by JohnAshburner** [comment]
See [https://github.com/plutoniusz](https://github.com/plutoniusz)

**Comment by plutoniusz** [comment]
Hi,

thank you. Yes, that works for me for the whole dataset. I have now identified that the values change once I also use nitorch.tools.qmri.io.GradientEchoMulti.from_fnames() that I used before creating maps with nitorch.tools.qmri.relax.greeq(). Based on what you sent I added that step:


```
from nitorch.tools.img_statistics import estimate_noise
import os
import nitorch.tools.qmri.io as qio

cwd = os.getcwd()
p = os.path.join(cwd, "MPM/t1w_mfc_3dflash_v1i_R4_0015")
#t1w = str(os.path.join(p, 'anon_s2018-02-28_18-26-190921-00001-00224-1.nii'))

t1w = []
for filename in os.listdir(str(p)):
    if filename.endswith(".nii"):
        t1w.append(str(os.path.join(p, filename)))
    else:
        continue

t1w = qio.GradientEchoMulti.from_fnames(t1w)

for e in t1w:
    print(e)
    sd_noise = estimate_noise(e.fdata())[0]
    print(sd_noise)  
# GradientEcho(shape=(280, 320, 224)) 
# tensor(59.0657, dtype=torch.float64)
```

Is that expected? I think that the parameter maps created with the qmri.greeq() looked more denoised than expected although I am not sure.

**Comment by plutoniusz** [comment]
The values seem to be correct now, around 18 for this dataset. I think there are two prints left in img_statistics.py lines 148 and 153.

**Comment by JohnAshburner** [comment]
I was sure I had the following working (line 128 of  nitorch/tools/img_statistics.py):
        dat = dat.fdata(rand=True, missing=0)

An earlier workaround simply involved inserting W[0]=0. at about line 152, but this is a bit messy.

**Comment by balbasty** [comment]
I think that the `missing` keyword only exists in the qmri-specific io, but not in the general io module. Maybe I should also add this missing stuff in the main io?

**Comment by JohnAshburner** [comment]
Thanks for re-opening. That would be helpful Yael. I got a bit confused when I found the missing option didn't work in some other tests I was trying - although I have to admit I didn't spend too long trying to figure it all out.

**Comment by balbasty** [comment]
What do you think we should do with values considered as missing (apart from not sampling noise): keep their original value / replace them with 0 / replace them with NaN / ... ? I feel like making them NaN (when the datatype is a floating point) is elegant and simplifies downstream code, but it means we have to be very careful not to call reduction functions (like min or sum) on them without masking out NaNs first.

**Comment by JohnAshburner** [comment]
I tend to use NaNs, and try to take care about handling them properly.  Reduction functions are likely to give incorrect values whatever code is included in the data (and the 999 code for SPSS missing data has probably been the cause of a lot of dodgy stats).  With NaNs, you at least see that you are not handling missing values properly.  Julia has a framework for handling missingness.  I don't know about Python/Torch.

**Comment by balbasty** [comment]
It should be done in this commit: 239060f9e90b76a7d525cb7ada0ac93b8fb8d421
