### ISSUE TITLE
nitorch._C.solve.c_regulariser

### ISSUE THREAD

**Issue by JohnAshburner** [balbasty/nitorch#69]
I've probably messed up the installation, but I get the following error when I try to run ``_greeq`` using ``opt.backend.device = 'cpu'``

  ```
File "/home/john/miniconda3/lib/python3.9/site-packages/nitorch/spatial/_regularisers.py", line 1166, in regulariser
    return c_solvers.c_regulariser(
AttributeError: module 'nitorch._C.solve' has no attribute 'c_regulariser'

```

**Comment by balbasty** [comment]
Hi John,

There was a mistake in a check, which should be fixed.

But you are indeed using the non-compiled version, which will make greeq a bit slow. To compile the C sources, you need to define the environment variable `NI_COMPILED_BACKEND="C"` before `pip install` (if you don't have a GPU, it will only compile the pure C++ sources, not the CUDA stuff).
Let me know if you want me to send you a pre-compiled version (I'll need your python and pytorch versions + your type of GPU if you have one)

Cheers
Yael
