### ISSUE TITLE
Error: 'list' object has no attribute 'update'

### ISSUE THREAD

**Issue by Jerzy97** [balbasty/nitorch#71]
Dear Yael,

I ran into the error `'list' object has no attribute 'update'` when calling the method `qmri.io.GradientEchoMulti.from_instance(old)`.
I believe the issue is here
https://github.com/balbasty/nitorch/blob/1787998512ae11c09b32785d6167bbd972d3bceb/nitorch/tools/qmri/io.py#L262

In particular the `[getattr(instance, key) ...]` should be changed to `{key: getattr(instance, key) ...}`, as otherwise we will create a list instead of dict.
Let me know if I missed something or made a mistake.

Thanks for developing this code!
Regards, Georg

**Comment by balbasty** [comment]
Hi Georg, 

You're absolutely right, thanks for reporting!

Cheers
Yael
