### ISSUE TITLE
ModuleNotFoundError: No module named 'interpol'

### ISSUE THREAD

**Issue by ivandiazzz** [balbasty/nitorch#80]
I am trying to install nitorch. I followed the instructions with and without C++/CUDA extensions.

I get the following error when I try

` import nitorch` 

ModuleNotFoundError: No module named 'interpol'
The error seems to come from nitorch/_C/grid.py:4

**Comment by balbasty** [comment]
Hi @ivandiazzz 

Thanks, there was a dependency (to [`torch-interpol`](https://github.com/balbasty/torch-interpol)) missing. I just added it, let me know if it fixes it.

I am sorry, I've just merged lots if changes yesterday so, there may be a few other mistakes like this.

**Comment by ivandiazzz** [comment]
Excellent. Installing torch-interpol fixed the issue. Thank you for your quick reply.
